version: "3.1"

services:
  api:
    build: ./src/anomaly
    image: anomaly_base:latest
    restart: always
    volumes:
      - .certs:/certs
      - /root/web_data:/app/static
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      MODEL_SERVICE_IP: ${MODEL_SERVICE_IP}
  database:
    image: mongo:4.4.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /home/vps/mongodata:/data/db
