version: "3.4"

services:
  api:
    build: ./src/anomaly
    image: anomaly_base:latest
    restart: always
    volumes:
      - .certs:/certs
      - /home/vps/web_data:/app/static
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      MODEL_SERVICE_IP: ${MODEL_SERVICE_IP}
  database:
    image: mongo:4.4.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /home/vps/mongodata:/data/db
  backup:
    image: ubuntu:latest
    container_name: mongo_backup
    restart: always
    env_file:
      - .env
    volumes:
      - /home/vps/mongodata:/data/db
      - /home/vps/mongobackups:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      bash -c "apt-get update && apt-get install -y cron && echo '0 3 * * * /path/to/backup.sh' | crontab - && cron -f"
