version: "3.4"

services:
  api:
    build: .
    image: anomaly_base:latest
    restart: always
    volumes:
      - .certs:/certs
    ports:
      - "443:443"
    env_file:
      - .env

    depends_on:
      - database
  database:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .menv
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - data:/data_md/db

volumes:
  data: