version: "3.4"

services:
  api:
    build: .
    image: anomaly_base:latest
    restart: always
    volumes:
      - .certs:/certs
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - /data/static:/app/static
    depends_on:
      - database
  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /data/mongo:/data/db