version: "3.4"

services:
  api:
    build: .
    image: anomaly_base:latest
    restart: always
    volumes:
      - .certs:/certs
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - /home/vps/web_data:/app/static
    depends_on:
      - database
  database:
    image: mongo:4.4.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /home/vps/mongodata:/data/db
  anomaly_bot:
    image: anomaly_bot:latest
    restart: always
    ports:
      - "8123:8123"