version: "3.4"

services:
  api:
    build: .
    image: anomaly_base:latest
    ports:
      - "24000:24000"
    env_file:
      - .env

    depends_on:
      - database
  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: LOGIN
      MONGO_INITDB_ROOT_PASSWORD: PASSWD
    ports:
      - 27017:27017
    env_file:
      - mongo_credentials.env
    volumes:
      - data:/data_md/db
volumes:
  data: