version: "3.1"

services:
  api:
    build: .
    image: anomaly_base:latest
    ports:
      - "24000:24000"
    env_file:
      - .env
    
    depends_on:
      - database
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    env_file:
      - .env
volumes:
  data:

